server:
  port: 8089
spring:
  servlet:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 1000Mb
  thymeleaf:
    cache : false
    mode: HTML5
  neo4j:
      url: bolt://192.168.25.209:7687
      username: neo4j
      password: 123456
file:
  serverurl:  http://localhost:8089
  location : D:\\kgmanager\\csv   #如果是Windows情况下，格式是 D:\\kgmanager\\csv   linx 格式"/home/kgmanager/csv";